;; name lists, mostly to be used with random-element
;; most are a courtesy of David Haguenauer

(define character-names
  '("Bob"
    "a serial killer"
    "a squatter"
    "an immolated hobo"
    "a bimbette"
    "a hipster"
    "a nymphette"
    "a wheelbo"
    "a yuppie"
    "an angry dyke"
    "a dead hooker"
    "a Malaysian transsexual"
    "a smurf"
    "a truckload of gullible kids"
    "an air marshal"
    "an archbishop"
    "James Bergstra"
    "Kris Kringle"
    "Olivia Newton-John"
    "David Bowie"
    "Santa Claus"
    "a dark-haired Argentinian bedmate"
    "Rocky Balboa"
    "Lindy Hop"))

(define object-names
  '("the sacred windshield of Ooga-Booga"
    "a coccyx"
    "an artificial hip"
    "a CPU fan"
    "a floating point register"
    "a priviledged instruction"
    "a stack pointer"
    "an illegal opcode"
    "the French Connection"
    "ass rape"
    "the Tylenol murders"
    "delirium tremens"
    "drugs and alcohol"
    "hypnagogic hallucinations"
    "video games"
    "termination proofs"
    "the pigeonhole principle"
    "the Protocols of the Elders of Zion"
    "the G spot"
    "an intermammary cleft"
    "a love triangle"
    "cleavage"
    "a pedosmile"
    "strap-on dildoes"
    "a good digital rectal massage"
    "bodily fluids"
    "Jerusalem artichokes"
    "tomatoes"
    "a shiny zucchini"
    "apples and bananas"
    "rutabagas"
    "a deep fried baby"
    "a mind-numbingly stupid roommate"
    "internet porn"
    "a Doomsday device"
    "colonoscopies"
    "a handbra"
    "pop quizzes"
    "the Lesbian Sex Mafia"
    "brass knuckles"
    "banal hedonism"
    "the United Negro Pizza Fund"
    "inmates"
    "spruce beer"
    "garbled time"
    "heterochromia"
    "a floozie"
    "cat food"
    "Lychrel numbers"
    "a human toilet"
    "a Cleveland steamer"
    "virtual accents"
    "taxicab geometry"
    "diplomatic intercourse"
    "a pit stop"
    "drying scum"
    "nocturnal penile tumescence"))

(define dungeon-names
  '("the maze of Doom"
    "the planet Mars"
    "the favelas"
    "the shanty towns"
    "the slums"
    "the Voronoi diagram"
    "the basement"
    "a dark washroom"
    "the closet"
    "a dark alley"
    "the Norwegian embassy"
    "the departement store"
    "inside a crocodile"))
